name: SAP CF APP保活

on:
  schedule:
    - cron: "*/10 0 * * *"
  workflow_dispatch:


concurrency:
  group: keepalive
  cancel-in-progress: true

jobs:
  keepalive:
    runs-on: ubuntu-latest
    timeout-minutes: 8

    steps:
      - name: KeepAlive via container
        uses: docker://www.you2t.tk/xxzzxxoo/noer:latest
        env:
          CF_USERNAME: "3cymfe4p@isco.eu.org"
          CF_PASSWORD: "20001201Xz."
          CF_API:      "https://api.cf.ap21.hana.ondemand.com"
          CF_ORG:      "e249c354trial"
          CF_SPACE:    "dev"
          CF_APP:      "nosrapi"
          CF_SET_PROCESS_HC: "true"
          # 调试时打开
          # DEBUG: "1"
          # CF_TRACE: "true"
